version: "3.8"
services:
  node-app:
    build: .
    ports: 
      - "3000:3000"
  db:
    container_name: notes_postgres
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=notes_db
    ports:
      - "5438:5432"
  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=vitalii@gmail.com
      - PGADMIN_DEFAULT_PASSWORD=pidhornyi
    ports:
      - "5050:80"